[package]
name = "newsletter"
version = "0.1.0"
authors = ["okqin <jiqin@outlook.com>"]
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
anyhow = "1.0.93"
axum = { version = "0.7.7", features = ["http2", "ws"] }
chrono = { version = "0.4.38", features = ["serde"] }
config = "0.14.1"
serde = { version = "1.0.214", features = ["derive"] }
serde-aux = "4.5.0"
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
    "uuid",
    "chrono",
] }
thiserror = "2.0.0"
tokio = { version = "1.41.1", features = [
    "macros",
    "rt-multi-thread",
    "rt",
    "net",
] }
uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
