[package]
name = "newsletter"
version = "0.1.0"
authors = ["okqin <jiqin@outlook.com>"]
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
anyhow = "1.0.92"
axum = { version = "0.7.7", features = ["http2", "ws"] }
config = "0.14.1"
serde = { version = "1.0.214", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio", "tls-rustls", "uuid", "chrono"] }
tokio = { version = "1.41.0", features = [
    "macros",
    "rt-multi-thread",
    "rt",
    "net",
] }

[dev-dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
