[server]
host = "0.0.0.0"
port = 8000
base_url = "http://localhost"

[database]
host = "127.0.0.1"
port = 5432
username = "app"
password = "secret"
db_name = "newsletter"
require_ssl = true

[logs]
# The directive syntax is similar to that of env_logger’s.
# At a high level, the syntax for directives consists of several parts:
# "target[span{field=value}]=level"
# If not configured, the default is to log all info level messages.
directives = "info"

# The path to the log file.
# if not configured, logging to file is disabled.
#path = "/tmp"

[email_client]
base_url = "https://api.postmarkapp.com"
sender_email = "chin@jiqin.org"
authorization_token = "secret"
timeout_millis = 2000
