[server]
host = "0.0.0.0"
port = 8000

[database]
require_ssl = true

[logs]
# The directive syntax is similar to that of env_logger’s.
# At a high level, the syntax for directives consists of several parts:
# "target[span{field=value}]=level"
# If not configured, the default is to log all info level messages.
directives = "info"

# The path to the log file.
# if not configured, logging to file is disabled.
#path = "/tmp"
